#! /bin/bash
# Helper script to update *my* repository

repodir=$HOME/workdir/aur-fedora-mingw/pkg

die() {
    echo "$@" >&2
    exit 1
}

[ -n "$1" -a -z "$2" ] || die "Usage: $0 DIRECTORY"
[ -e "$1/PKGBUILD" ] || die "'$1' must be a package directory"

repoupdate=./repo-update
[ -x $repoupdate ] || repoupdate=../repo-update
[ -x $repoupdate ] || repoupdate=repo-update
[ -x $repoupdate ] || die "repo-update script not found in PATH, . or .."

# Remove old packages
rm -f $repodir/$1-*.pkg.tar.xz

# Build new package
pushd "$1" > /dev/null
makepkg
popd > /dev/null
[ -r "$1"/*.pkg.tar.xz ] || die "Package compilation failed"

# Upgrade installed package
yes | LC_MESSAGES=C yaourt -U "$1"/*.pkg.tar.xz || die "Package upgrade failed"

# Update repository
$repoupdate $repodir/entidi "$1"/*.pkg.tar.xz || die "$repoupdate failed"

# Clean up build files
rm -fr "$1"/pkg "$1"/src "$1"/*.pkg.tar.xz
