#!/bin/sh
#
# A wrapper for mingw-w64-python2 that runs python2.exe through wine.
#
# If this is the first call, we need to set WINEPREFIX to a non-existent
# path [1] under a directory owned by the current user. If this is not
# the first call, we should reuse the above WINEPREFIX (hence that
# prefix should be computable).
#
# The arch (win32 or win64) is injected into this file by PKGBUILD.
#
# [1] Otherwise wine will always create a win64 environment, regardless
#     of the WINEARCH environment variable content:
#     https://bugs.winehq.org/show_bug.cgi?id=29661

tmp="$TMPDIR"
[ -z "$tmp" ] && tmp=/tmp
[ @arch@ = win32 ] && host=i686-w64-mingw32 || host=x86_64-w64-mingw32

mkdir -p "$tmp/$USER/winepython"
WINEARCH=@arch@ WINEPREFIX="$tmp/$USER/winepython/@arch@" DISPLAY= /usr/bin/wine /usr/$host/bin/python${_pybasever}.exe "$@"
