#!/bin/bash
# This file can either be executed or sourced. If sourced, environment
# modifications are retained. See mingw-configure for documentation.

source "$(dirname ${BASH_SOURCE[0]})/mingw-configure"
call_configure i686-w64-mingw32 32 "$@"
