#!/bin/bash

# The first argument should always be the directory where configure resides
path_to_configure="$1"
shift

arch=x86_64-w64-mingw32 \

export PATH="/usr/$arch/bin:$PATH"
"$path_to_configure/configure" \
    CFLAGS="${MINGW_CFLAGS:--O2 -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions --param=ssp-buffer-size=4} $MINGW64_CFLAGS" \
    CPPFLAGS="$MINGW_CPPFLAGS $MINGW64_CPPFLAGS" \
    LDFLAGS="$MINGW_LDFLAGS $MINGW64_LDFLAGS" \
    CXXFLAGS="${MINGW_CXXFLAGS:--O2 -pipe -Wall} $MINGW64_CXXFLAGS" \
    --build="$CHOST" \
    --host=$arch \
    --prefix=/usr/$arch \
    "$@"
