#! /bin/bash
# Helper script to update *my* repository

die() {
    echo "$@" >&2
    exit 1
}

case "$1" in
    i686|x86_64)
        arch=$1
        dir=$2
        pkg=$arch-$2
        ;;
    *)
        arch=native
        dir=$1
        pkg=$1
        ;;
esac

root=$(dirname ${BASH_SOURCE[0]})
repodir=$(source /usr/share/mingw/makepkg.common.conf; echo $PKGDEST)
repoupdate="$root/repo-update"

[ -n "$dir" ] || die "Usage: $0 [i686|x86_64] DIRECTORY"
[ -e "$root/$dir/PKGBUILD" ] || die "'$1' must be a package directory"

# Remove old packages
rm -f $repodir/$pkg-*.pkg.tar.xz

# Build new package
pushd "$root/$dir" > /dev/null
makepkg --config /usr/share/mingw/makepkg.$arch.conf
popd > /dev/null
[ -r "$root/$dir"/*.pkg.tar.xz ] || die "Package compilation failed"

# Upgrade installed package
yes | LC_MESSAGES=C yaourt -U "$root/$dir"/*.pkg.tar.xz || die "Package upgrade failed"

# Update repository
$repoupdate $repodir/entidi "$root/$dir"/*.pkg.tar.xz || die "$repoupdate failed"

# Clean up build files
rm -fr "$root/$dir/pkg" "$root/$dir/src" "$root/$dir"/*.pkg.tar.xz
