#!/bin/sh
#
# A wrapper for running an exe through wine.
#
# If this is the first call, we need to set WINEPREFIX to a non-existent
# path [1] under a directory owned by the current user. If this is not
# the first call, we should reuse the above WINEPREFIX (hence that
# prefix should be computable).
#
# The arch (win32 or win64) and the exe file are injected by PKGBUILD.
#
# [1] Otherwise wine will always create a win64 environment, regardless
#     of the WINEARCH environment variable content:
#     https://bugs.winehq.org/show_bug.cgi?id=29661

prefix="$TMPDIR"
[ -z "$prefix" ] && prefix=/tmp
prefix="$prefix/$(whoami)/gi-wine"

mkdir -p "$prefix"
WINEARCH=@arch@ WINEPREFIX="$prefix/@arch@" DISPLAY= /usr/bin/wine @exe@ "$@"
